#define yy_create_buffer zz_create_buffer
#define yy_delete_buffer zz_delete_buffer
#define yy_scan_buffer zz_scan_buffer
#define yy_scan_string zz_scan_string
#define yy_scan_bytes zz_scan_bytes
#define yy_flex_debug zz_flex_debug
#define yy_init_buffer zz_init_buffer
#define yy_flush_buffer zz_flush_buffer
#define yy_load_buffer_state zz_load_buffer_state
#define yy_switch_to_buffer zz_switch_to_buffer
#define yyin zzin
#define yyleng zzleng
#define yylex zzlex
#define yyout zzout
#define yyrestart zzrestart
#define yytext zztext
#define yywrap zzwrap

/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
static yyconst short int yy_accept[200] =
    {   0,
        0,    0,    0,    0,   34,   34,   58,   57,   37,   40,
       57,   57,   25,   26,   29,   22,   57,   55,   57,   47,
       30,   31,   57,   27,   55,   23,   24,   32,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   39,   57,   55,   46,   55,   55,   55,   55,   55,
       34,   35,   37,    0,   56,    0,   38,    0,   47,   55,
       55,   45,   33,   43,    0,   28,   55,   13,   55,   55,
       55,   55,   55,    3,   55,   55,   55,   55,   55,   55,
       55,    4,   55,   39,   46,   55,   49,   55,   55,    0,
       53,   55,   55,   34,   35,   35,   36,   45,   55,   43,

        0,    0,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   15,   55,   55,   55,   55,
       55,   55,   55,   55,    0,    0,   55,    0,   41,   55,
       55,   55,   18,   55,    2,   21,   55,   20,   55,   55,
       55,   55,   19,   17,   55,   48,   50,   55,   55,   55,
       44,   44,   42,   12,   10,   16,   55,   55,    5,    1,
       55,   55,   55,   55,   55,    0,   52,   55,   55,   55,
       55,   55,   55,   11,   55,   55,    7,   55,   14,    8,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,    9,    6,   55,    0,   51,    0,   54,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,    1,    1,    1,   20,   21,   21,   22,   23,   21,
       21,   21,   21,   21,   21,   24,   21,   25,   21,   21,
       21,   21,   21,   21,   26,   21,   21,   21,   21,   21,
       27,   28,   29,    1,   28,   30,   31,   32,   33,   34,

       35,   21,   36,   37,   38,   21,   21,   39,   40,   41,
       42,   43,   21,   44,   45,   46,   47,   21,   21,   48,
       49,   50,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    3,    3,    3,    3,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    1,    3,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        4,    3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[207] =
    {   0,
        0,    0,   48,   91,  267,  263,  268,  766,   50,  766,
      234,  235,  766,  766,  766,  766,   40,   44,  221,   51,
      766,  766,  196,  766,   55,  766,  766,  766,   63,   70,
       95,   89,   53,   76,   63,   96,  106,  110,  116,  117,
      124,  196,   99,  135,  155,  145,  146,   55,  155,  161,
        0,   62,  123,  190,  766,  183,  766,  161,  166,    0,
      167,   73,  766,  187,  130,  766,  174,  175,  184,  190,
      194,  198,  204,  210,  214,  220,  221,  227,  228,  238,
      244,  248,  254,  157,  279,  261,  267,  271,  284,  162,
      766,  280,  292,    0,  210,  241,  766,  297,  134,  315,

      163,  114,  298,  305,  314,  315,  321,  328,  329,  335,
      345,  341,  351,  355,  364,  363,  370,  374,  383,  384,
      393,  399,  403,  392,  208,  106,   96,   84,   74,  409,
      415,  421,  422,  429,  433,  437,  443,  447,  453,  454,
      460,  464,  468,  472,  476,  482,  486,  490,  510,  497,
       65,   53,   50,  496,  503,  504,  511,  520,  519,  526,
      527,  533,  541,  542,  548,  277,  766,  549,  561,  560,
      567,  568,  575,  581,  587,  588,  594,  600,  604,  608,
      614,  618,  622,  626,  630,  636,  642,  648,  649,  656,
      690,  662,  666,  700,  309,  766,  326,  766,  766,  742,

      746,  750,  752,  756,  760,  761
    } ;

static yyconst short int yy_def[207] =
    {   0,
      199,    1,    1,    1,  200,  200,  199,  199,  199,  199,
      201,  202,  199,  199,  199,  199,  199,  203,  199,  199,
      199,  199,  199,  199,  203,  199,  199,  199,  203,  203,
      203,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,  199,  199,   31,  199,   31,   31,   31,   31,   31,
      204,  205,  199,  201,  199,  202,  199,  199,  199,  206,
       31,  206,  199,  199,  199,  199,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,  199,  199,   31,   31,   31,   31,  199,
      199,   31,   31,  204,  205,  205,  199,  199,  206,  199,

      199,  199,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,  199,  199,  206,  199,  199,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
      199,  206,  199,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,  199,  199,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,  199,  199,  199,  199,    0,  199,

      199,  199,  199,  199,  199,  199
    } ;

static yyconst short int yy_nxt[817] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,    8,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   25,   25,   25,   25,   25,   26,    8,   27,   28,
       29,   30,   31,   32,   33,   25,   25,   34,   35,   36,
       37,   25,   38,   25,   39,   40,   41,   25,   25,   25,
       42,   53,   58,   53,   59,   60,   90,   60,   62,   43,
       44,   91,   45,   64,  153,   59,   60,  152,   60,   60,
       96,   60,   46,   65,   60,   97,   60,   60,   47,  151,
       48,   60,   60,   60,   60,   65,   49,   62,  129,   61,
       60,   61,   50,   42,   61,   99,   67,   60,  153,   61,

       73,   61,   43,   44,   75,   45,   60,   99,   60,   60,
      152,   58,   61,   85,   61,   46,   74,   61,   68,   72,
      151,   47,   60,   48,   53,   61,   53,   61,  129,   49,
       61,   69,   61,   70,   61,   50,   71,   76,   77,  102,
       78,  102,   61,  126,   61,  127,   61,   61,   61,   62,
       79,   61,   61,   81,   61,   61,   86,   61,   82,   84,
       61,   80,   61,   90,   87,   61,   83,   64,   91,   85,
       88,   61,  128,   61,  128,   98,   61,   65,   64,   67,
       59,   61,   61,   61,   61,   57,   61,   61,   65,   65,
       89,   61,   92,   61,   55,   79,   75,   61,   84,   61,

       65,  100,   61,   61,  103,   61,   93,   66,   61,  101,
       61,   61,   61,   61,  104,   61,   61,  126,  199,  126,
       61,  101,   61,  199,  105,   61,   61,  106,   61,   63,
       61,   61,   61,  107,   61,   61,   61,   57,   55,   61,
       61,  109,   61,  108,  111,   61,   61,  110,   61,   96,
       61,   61,   61,  112,   97,   61,   61,  114,   61,   61,
      113,   61,   61,   61,   61,   61,   61,  199,   61,   61,
      115,   52,  117,  116,   61,   52,   61,  199,  166,   61,
       61,  118,   61,  167,   61,   61,   61,  119,  199,   61,
       61,   64,   61,   85,  121,   61,  122,   61,  120,   61,

      199,   65,   61,   61,  199,   61,  199,   61,   61,   61,
      195,   98,   61,   65,  199,  196,   61,  199,   61,  125,
       61,   61,   61,  199,  123,   61,  117,  197,   61,  100,
       61,  125,  198,   61,   61,  124,   61,  101,  199,   61,
      130,   61,  131,   61,  132,  133,   61,  199,  199,  101,
       61,   61,   61,   61,  199,   61,   61,   61,  135,   61,
      199,  199,   61,  134,   61,   61,   61,   61,  199,   61,
       61,   61,  199,   61,  136,  139,   61,   61,  138,   61,
      137,   61,   61,   61,  199,  141,   61,   61,  140,   61,
      199,   61,   61,   61,  142,  199,   61,  199,  199,   61,

       61,   61,   61,  199,   61,   61,   61,  199,   61,  143,
       61,   61,   61,  145,  144,   61,  147,  199,  199,   61,
       61,   61,   61,  146,   61,   61,  199,  199,   61,   61,
       61,   61,  199,   61,   61,   61,  148,   61,  150,   61,
       61,   61,  199,  199,   61,   61,  199,   61,  149,  199,
       61,   61,  199,   61,  154,  155,   61,   61,   61,   61,
       61,  199,   61,   61,  156,   61,  157,   61,  199,   61,
       61,   61,  199,   61,   61,   61,  199,  199,   61,   61,
      158,   61,  199,   61,   61,   61,  199,  159,   61,   61,
       61,  160,   61,  199,   61,   61,   61,  162,   61,  161,

       61,   61,   61,  163,   61,   61,   61,  199,   61,   61,
       61,  166,   61,   61,   61,  199,  167,   61,   61,  199,
       61,  164,   61,   61,   61,  199,   61,   61,   61,  168,
      165,   61,   61,   61,   61,   61,  199,   61,   61,   61,
       61,   61,   61,  199,   61,   61,   61,   61,   61,  169,
      170,   61,   61,  199,  199,   61,   61,   61,   61,  199,
       61,   61,   61,   61,   61,   61,  199,   61,  171,   61,
      199,   61,  199,  172,   61,  173,  174,   61,   61,   61,
       61,  199,   61,   61,   61,   61,   61,   61,  199,   61,
       61,  199,  199,  175,  176,  177,   61,   61,  178,   61,

      199,   61,   61,   61,   61,   61,   61,  199,   61,   61,
      179,   61,  180,   61,  199,  199,   61,   61,  199,   61,
      181,  182,   61,   61,   61,   61,   61,  199,   61,   61,
       61,  199,   61,  199,  183,   61,   61,  184,   61,  199,
       61,   61,   61,  199,   61,   61,   61,  199,  185,   61,
       61,  199,   61,  186,   61,   61,   61,  199,   61,   61,
       61,  199,   61,   61,   61,  187,   61,   61,   61,  199,
      190,   61,   61,  189,   61,  188,  191,   61,   61,  199,
       61,  199,  192,   61,   61,   61,   61,   61,  199,   61,
       61,  195,   61,  193,   61,  199,  196,   61,   61,  194,

       61,  197,   61,   61,   61,  199,  198,   61,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,   61,  199,   61,  199,
      199,   61,  199,  199,  199,  199,   61,  199,   61,  199,
      199,   61,   51,   51,   51,   51,   54,   54,   54,   54,
       56,   56,   56,   56,   61,   61,   94,  199,   94,   94,
       95,   95,   95,   60,   60,    7,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,

      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199
    } ;

static yyconst short int yy_chk[817] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    9,   17,    9,   17,   18,   48,   18,   18,    3,
        3,   48,    3,   20,  153,   20,   25,  152,   25,   25,
       52,   18,    3,   20,   29,   52,   29,   29,    3,  151,
        3,   30,   25,   30,   30,   20,    3,   62,  129,   33,
       29,   33,    3,    4,   33,   62,   29,   30,  128,   35,

       33,   35,    4,    4,   35,    4,   31,   62,   31,   31,
      127,   43,   34,   43,   34,    4,   34,   34,   30,   32,
      126,    4,   31,    4,   53,   32,   53,   32,  102,    4,
       32,   31,   36,   31,   36,    4,   31,   36,   37,   65,
       38,   65,   37,   99,   37,   99,   38,   37,   38,   44,
       39,   38,   39,   40,   39,   40,   44,   39,   40,   84,
       41,   39,   41,   90,   46,   41,   41,   45,   90,   45,
       46,   44,  101,   44,  101,   58,   44,   45,   59,   47,
       59,   46,   47,   46,   47,   56,   46,   47,   59,   45,
       47,   49,   49,   49,   54,   50,   49,   50,   42,   50,

       59,   64,   50,   61,   67,   61,   50,   23,   61,   64,
       67,   68,   67,   68,   69,   67,   68,  125,   95,  125,
       69,   64,   69,   95,   70,   69,   70,   71,   70,   19,
       71,   70,   71,   71,   72,   71,   72,   12,   11,   72,
       73,   73,   73,   72,   75,   73,   74,   74,   74,   96,
       75,   74,   75,   76,   96,   75,   76,   77,   76,   77,
       76,   76,   77,   78,   79,   78,   79,    7,   78,   79,
       78,    6,   80,   79,   80,    5,   80,    0,  166,   80,
       81,   81,   81,  166,   82,   81,   82,   83,    0,   82,
       83,   85,   83,   85,   88,   83,   89,   86,   86,   86,

        0,   85,   86,   87,    0,   87,    0,   88,   87,   88,
      195,   98,   88,   85,    0,  195,   92,    0,   92,   98,
       89,   92,   89,    0,   92,   89,   93,  197,   93,  100,
       93,   98,  197,   93,  103,   93,  103,  100,    0,  103,
      103,  104,  104,  104,  105,  106,  104,    0,    0,  100,
      105,  106,  105,  106,    0,  105,  106,  107,  108,  107,
        0,    0,  107,  107,  108,  109,  108,  109,    0,  108,
      109,  110,    0,  110,  109,  112,  110,  112,  111,  112,
      110,  111,  112,  111,    0,  114,  111,  113,  113,  113,
        0,  114,  113,  114,  115,    0,  114,    0,    0,  116,

      115,  116,  115,    0,  116,  115,  117,    0,  117,  117,
      118,  117,  118,  119,  118,  118,  121,    0,    0,  119,
      120,  119,  120,  120,  119,  120,    0,    0,  124,  121,
      124,  121,    0,  124,  121,  122,  122,  122,  124,  123,
      122,  123,    0,    0,  123,  130,    0,  130,  123,    0,
      130,  131,    0,  131,  130,  131,  131,  132,  133,  132,
      133,    0,  132,  133,  132,  134,  134,  134,    0,  135,
      134,  135,    0,  136,  135,  136,    0,    0,  136,  137,
      137,  137,    0,  138,  137,  138,    0,  137,  138,  139,
      140,  139,  140,    0,  139,  140,  141,  141,  141,  140,

      142,  141,  142,  142,  143,  142,  143,    0,  144,  143,
      144,  149,  145,  144,  145,    0,  149,  145,  146,    0,
      146,  145,  147,  146,  147,    0,  148,  147,  148,  150,
      148,  148,  154,  150,  154,  150,    0,  154,  150,  155,
      156,  155,  156,    0,  155,  156,  149,  157,  149,  157,
      158,  149,  157,    0,    0,  159,  158,  159,  158,    0,
      159,  158,  160,  161,  160,  161,    0,  160,  161,  162,
        0,  162,    0,  162,  162,  163,  164,  163,  164,  163,
      164,    0,  163,  164,  165,  168,  165,  168,    0,  165,
      168,    0,    0,  165,  168,  169,  170,  169,  170,  169,

        0,  170,  169,  171,  172,  171,  172,    0,  171,  172,
      171,  173,  172,  173,    0,    0,  173,  174,    0,  174,
      173,  175,  174,  175,  176,  175,  176,    0,  175,  176,
      177,    0,  177,    0,  176,  177,  178,  178,  178,    0,
      179,  178,  179,    0,  180,  179,  180,    0,  181,  180,
      181,    0,  181,  182,  182,  181,  182,    0,  183,  182,
      183,    0,  184,  183,  184,  183,  185,  184,  185,    0,
      186,  185,  186,  185,  186,  184,  187,  186,  187,    0,
      187,    0,  188,  187,  188,  189,  188,  189,    0,  188,
      189,  191,  190,  189,  190,    0,  191,  190,  192,  190,

      192,  194,  193,  192,  193,    0,  194,  193,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  191,    0,  191,    0,
        0,  191,    0,    0,    0,    0,  194,    0,  194,    0,
        0,  194,  200,  200,  200,  200,  201,  201,  201,  201,
      202,  202,  202,  202,  203,  203,  204,    0,  204,  204,
      205,  205,  205,  206,  206,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,

      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.ll"
#define INITIAL 0
/* -*-C++-*- */
#line 3 "scanner.ll"
#include <iostream>
#include <cstring>
#include <compiler/ParseTree.h>
#include "parser.h"
  YY_BUFFER_STATE main_buffer = 0;
  void return_to_main_buffer();
#define RDATA 1

#define COMMENT 2

#line 649 "scanner.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 19 "scanner.ll"


#line 803 "scanner.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 200 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 766 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "scanner.ll"
zzlval.intval=MODEL; return MODEL;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "scanner.ll"
zzlval.intval=DATA; return DATA;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "scanner.ll"
zzlval.intval=IN; return IN;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "scanner.ll"
zzlval.intval=TO; return TO;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 25 "scanner.ll"
zzlval.intval=INITS; return INITS;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 26 "scanner.ll"
zzlval.intval=PARAMETERS; return PARAMETERS;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "scanner.ll"
zzlval.intval=COMPILE; return COMPILE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "scanner.ll"
zzlval.intval=NCHAINS; return NCHAINS;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "scanner.ll"
zzlval.intval=INITIALIZE; return INITIALIZE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "scanner.ll"
zzlval.intval=CHAIN; return CHAIN;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "scanner.ll"
zzlval.intval=UPDATE; return UPDATE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "scanner.ll"
zzlval.intval=ADAPT; return ADAPT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "scanner.ll"
zzlval.intval=BY; return BY;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 37 "scanner.ll"
zzlval.intval=MONITOR; return MONITOR;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 38 "scanner.ll"
zzlval.intval=SET; return SET;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 39 "scanner.ll"
zzlval.intval=CLEAR; return CLEAR;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 40 "scanner.ll"
zzlval.intval=THIN; return THIN;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 42 "scanner.ll"
zzlval.intval=CODA; return CODA;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 43 "scanner.ll"
zzlval.intval=STEM; return STEM;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "scanner.ll"
zzlval.intval=LOAD; return LOAD;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "scanner.ll"
zzlval.intval=EXIT; return EXIT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "scanner.ll"
return ',';
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "scanner.ll"
return '[';
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 50 "scanner.ll"
return ']';
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "scanner.ll"
return '(';
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "scanner.ll"
return ')';
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "scanner.ll"
return '=';
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "scanner.ll"
return ARROW;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "scanner.ll"
return '*';
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "scanner.ll"
return ':';
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "scanner.ll"
return ';';
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 58 "scanner.ll"
return '`';
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "scanner.ll"
BEGIN(COMMENT);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "scanner.ll"
/* Eat up anything that's not a '*'   */
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "scanner.ll"
/* Eat up '*'s not followed by a '/'  */
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "scanner.ll"
BEGIN(INITIAL);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "scanner.ll"
/* Eat whitespace */
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "scanner.ll"
/* Eat comments */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "scanner.ll"
/* Eat newlines */
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "scanner.ll"
return ENDCMD;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 70 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 73 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 82 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "scanner.ll"
{
  zzlval.val = atof(zztext); return DOUBLE;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 88 "scanner.ll"
{
  zzlval.intval = atoi(zztext); return INT;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 92 "scanner.ll"
return DIM;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 93 "scanner.ll"
return NA;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 94 "scanner.ll"
return R_NULL;
	YY_BREAK
case 51:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 95 "scanner.ll"
return STRUCTURE;
	YY_BREAK
case 52:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 96 "scanner.ll"
return LIST;
	YY_BREAK
case 53:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 97 "scanner.ll"
return 'c';
	YY_BREAK
case 54:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 98 "scanner.ll"
return ASINTEGER;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 100 "scanner.ll"
{ 
  zzlval.stringptr = new std::string(zztext);
  return NAME;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 105 "scanner.ll"
{
  zzlval.stringptr = new std::string(zztext);
  // Remove enclosing quotes
  zzlval.stringptr->erase(zzlval.stringptr->size() - 1, 1);
  zzlval.stringptr->erase(0, 1);
  return STRING;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 113 "scanner.ll"
yyterminate();
	YY_BREAK
case YY_STATE_EOF(RDATA):
#line 114 "scanner.ll"
{
  return_to_main_buffer();
  return ENDDATA;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 118 "scanner.ll"
ECHO;
	YY_BREAK
#line 1217 "scanner.cc"
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 200 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 200 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 199);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 118 "scanner.ll"


int zzwrap()
{
  return 1;
}

bool open_data_buffer(std::string const *name) {
  if (main_buffer) {
    return false;
  }
  FILE *file = fopen(name->c_str(),"r");
  if (file) {
    main_buffer = YY_CURRENT_BUFFER;
    yy_switch_to_buffer(yy_create_buffer(file, YY_BUF_SIZE ) );
    BEGIN(RDATA);
    return true;
  }
  else {
    return false;
  }
}

void return_to_main_buffer() {
  if (main_buffer && (main_buffer != YY_CURRENT_BUFFER)) {
    yy_delete_buffer (YY_CURRENT_BUFFER);
    yy_switch_to_buffer (main_buffer);
    main_buffer = 0;
  }
  BEGIN(INITIAL);  
}
